version: D0.1.{build}

configuration: Release

image: Visual Studio 2017

environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  SDL2_IDIR: c:\mylibs\include\SDL2

platform:
  - x64

install:
  - mkdir %SDL2_IDIR%
  - cd %TEMP%
  
  # SDL2
  - IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\SDL2-devel-%SDL2_VERSION%-mingw.tar.gz appveyor DownloadFile http://libsdl.org/release/SDL2-devel-%SDL2_VERSION%-mingw.tar.gz
  - 7z x SDL2-devel-%SDL2_VERSION%-mingw.tar.gz -so | 7z x -si -ttar -oC:\
  - echo y | xcopy C:\SDL2-%SDL2_VERSION%\i686-w64-mingw32\* %MINGW_PATH%\ /S
  - IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\SDL2_mixer-devel-2.0.1-mingw.tar.gz appveyor DownloadFile https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.1-mingw.tar.gz
  - 7z x SDL2_mixer-devel-2.0.1-mingw.tar.gz -so | 7z x -si -ttar -oC:\
  - echo y | xcopy C:\SDL2_mixer-2.0.1\i686-w64-mingw32\* %MINGW_PATH%\ /S
  - IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\SDL2_image-devel-2.0.1-mingw.tar.gz appveyor DownloadFile https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.1-mingw.tar.gz
  - 7z x SDL2_image-devel-2.0.1-mingw.tar.gz -so | 7z x -si -ttar -oC:\
  - echo y | xcopy C:\SDL2_image-2.0.1\i686-w64-mingw32\* %MINGW_PATH%\ /S
  

build:
  verbosity: normal
