version: D0.1.{build}

configuration: Release

environment:
  global:
    PROJECT_NAME: project-n2de

image: Visual Studio 2017
   
platform: x64


before_build:  
  # Install SDL2.
  - ps: Start-FileDownload https://www.libsdl.org/release/SDL2-devel-2.0.8-VC.zip -FileName sdl2.zip
  - ps: Expand-Archive sdl2.zip -DestinationPath sdl2
  - set LIB=%LIB%;C:\projects\project-n2de\s2D_Engine\Dependencies\SDL2

  
build:
  project: C:\projects\project-n2de\2D_Engine\2D_Engine.sln
  verbosity: normal
