version: '{branch}.{build}'

image: Visual Studio 2017
clone_depth: 1




before_build:
   - |-
    set PREFIX=C:\usr
   - |-
    %DEPENDS% mkdir %PREFIX%\include\SDL2
    %DEPENDS% mkdir %PREFIX%\lib
    %DEPENDS% cd %TEMP%
    
    %DEPENDS% appveyor DownloadFile https://www.libsdl.org/release/SDL2-devel-2.0.8-VC.zip
    %DEPENDS% 7z x SDL2-devel-2.0.8-VC.zip > nul
    %DEPENDS% copy SDL2-2.0.8\include\SDL2\* %PREFIX%\include > nul
    %DEPENDS% copy SDL2-2.0.8\lib\x64\*.a %PREFIX%\lib > nul

build_script:
  - |-
    cd %APPVEYOR_BUILD_FOLDER%
    del "C:\Program Files\Git\usr\bin\sh.exe"

# Build
  - |-
    copy %PREFIX%\lib\SDL2.dll C:\project-n2de
    copy %PREFIX%\lib\SDL2_image.dll C:\project-n2de
