version: D0.1.{build}

configuration: Release

image: Visual Studio 2017
   
platform: x64

environment:
    PREFIX: c:\usr_msvc
    MSVC:
    MINGW32: rem

before_build:  
  - ps: "Start-FileDownload https://www.libsdl.org/release/SDL2-devel-2.0.8-VC.zip"
  - cmd: "7z x SDL2-devel-2.0.8-VC.zip"
  
  - ps: "Start-FileDownload https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.3-VC.zip"
  - cmd: "7z x SDL2_image-devel-2.0.3-VC.zip"
  
  - cmd: "set SDL2_DEVEL_PATH=%APPVEYOR_BUILD_FOLDER%\\SDL2-devel-2.0.8-VC"
  - cmd: "set PATH=C:\\MinGW\\bin;%PATH%"
  
build:
  project: C:\projects\project-n2de\2D_Engine\2D_Engine.sln
  verbosity: normal
