version: D0.1.{build}

configuration: Debug

image: Visual Studio 2017
    
environment:
    PREFIX: c:\usr_msvc

before_build:
- |-
   %NEEDDEPENDS% mkdir %PREFIX%\include\SDL2
   %NEEDDEPENDS% mkdir %PREFIX%\lib
   
   %NEEDDEPENDS% appveyor DownloadFile http://www.libsdl.org/release/SDL2-devel-2.0.8-VC.zip
   %NEEDDEPENDS% 7z x SDL2-devel-2.0.8-VC.zip > nul
   %NEEDDEPENDS% copy SDL2-2.0.8\include\*  %PREFIX%\include > nul
   %NEEDDEPENDS% copy SDL2-2.0.8\lib\x64\*  %PREFIX%\lib > nul
  
build:
  project: C:\projects\project-n2de\2D_Engine\2D_GameEngine\2D_Engine.sln
  verbosity: normal

platform: x64
