version: '{branch}.{build}'

image: Visual Studio 2017
clone_depth: 1




before_build:
   - |-
    %DEPENDS% mkdir %PREFIX%\include\SDL2
    %DEPENDS% mkdir %PREFIX%\lib
    
    %DEPENDS% appveyor DownloadFile https://www.libsdl.org/release/SDL2-devel-2.0.8-VC.zip
    %DEPENDS% 7z x SDL2-devel-2.0.8-VC.zip > nul
    %DEPENDS% copy SDL2-2.0.8\include\* C:\projects\project-n2de\2D_Engine\2D_GameEngine > nul
    %DEPENDS% copy SDL2-2.0.8\lib\x64\* C:\projects\project-n2de\2D_Engine\2D_GameEngine > nul

build_script:
  - |-
    cd %APPVEYOR_BUILD_FOLDER%
    del "C:\Program Files\Git\usr\bin\sh.exe"

build:
