configuration: Release

image: Visual Studio 2017

build:
  verbosity: normal
  
install:
  - ps: Start-FileDownload https://www.libsdl.org/release/SDL2-devel-2.0.8-VC.zip 'dependencies/SDL2.zip'
  - ps: Expand-Archive dependencies/SDL2.zip -DestinationPath dependencies\
  - set LIB=%LIB%;C:\dependencies\SDL2_image-2.0.3\lib\64
  
  - ps: Start-FileDownload https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.3-VC.zip -FileName sdl2image.zip
  - ps: Expand-Archive sdl2image.zip -DestinationPath C:\projects\sdl2image
  - set LIB=%LIB%;C:\projects\sdl2image\SDL2_image-2.0.3\lib\64
